name: Custom Github Docker Action
description: Call API and get open port

inputs:
  ip:
    description: User IP, from 192.168.99.1 to 192.168.99.254
    required: true
    default: 192.168.99.1
outputs:
  open_port:
    description: Getted open port

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.ip }}
